//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResMensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResMensagens", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o texto inferior do meme.
        /// </summary>
        internal static string lblInformeTextoDown {
            get {
                return ResourceManager.GetString("lblInformeTextoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o texto superior do meme.
        /// </summary>
        internal static string lblInformeTextoUp {
            get {
                return ResourceManager.GetString("lblInformeTextoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto rodapé meme.
        /// </summary>
        internal static string lblTextoRodapeMeme {
            get {
                return ResourceManager.GetString("lblTextoRodapeMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto topo meme.
        /// </summary>
        internal static string lblTextoTopoMeme {
            get {
                return ResourceManager.GetString("lblTextoTopoMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde alguns segundos estou gerando o meme!.
        /// </summary>
        internal static string msgAguardeGerarndoMeme {
            get {
                return ResourceManager.GetString("msgAguardeGerarndoMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá, sou gerador de memes! .
        /// </summary>
        internal static string msgMemeBemVindo {
            get {
                return ResourceManager.GetString("msgMemeBemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o formulário abaixo para que eu possa gerar seu meme!.
        /// </summary>
        internal static string msgPreenchaFormularioMeme {
            get {
                return ResourceManager.GetString("msgPreenchaFormularioMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, você deve selecionar um meme e informar um texto para o meme!.
        /// </summary>
        internal static string msgTemplateTextoObrigatorio {
            get {
                return ResourceManager.GetString("msgTemplateTextoObrigatorio", resourceCulture);
            }
        }
    }
}
